// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAepoMDMuRxMzI7vKXynHceK_kvu4Wyioc',
    appId: '1:304717488484:android:c99a73571cb9eca6b45a71',
    messagingSenderId: '304717488484',
    projectId: 'chat-app-14724',
    storageBucket: 'chat-app-14724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZmPonsGeP8T3IKw-_wkIHvkcq92Qrt7E',
    appId: '1:304717488484:ios:ac511bfbe9406d68b45a71',
    messagingSenderId: '304717488484',
    projectId: 'chat-app-14724',
    storageBucket: 'chat-app-14724.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZmPonsGeP8T3IKw-_wkIHvkcq92Qrt7E',
    appId: '1:304717488484:ios:ac511bfbe9406d68b45a71',
    messagingSenderId: '304717488484',
    projectId: 'chat-app-14724',
    storageBucket: 'chat-app-14724.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}